package com.rtpledger.shared.message;

/**
 * Logical stages for transaction flow visualization.
 */
public enum FlowTraceStage {
    CLIENT_HTTP_ACCEPTED,
    CLIENT_HTTP_REJECTED,
    CLIENT_RING_PUBLISH_OK,
    CLIENT_RING_PUBLISH_REJECTED,
    CLIENT_NATS_PUBLISH_OK,
    CLIENT_NATS_PUBLISH_FAILED,
    SERVER_NATS_RECEIVED,
    SERVER_RING_ENQUEUED,
    SERVER_RING_REJECTED,
    SERVER_BALANCE_COMPUTE_OK,
    SERVER_BALANCE_COMPUTE_FAILED,
    SERVER_QUEUE_APPEND_OK,
    SERVER_QUEUE_APPEND_FAILED,
    SERVER_NATS_REPLY_OK,
    SERVER_NATS_REPLY_FAILED,
    DRAINER_BATCH_FLUSH_OK,
    DRAINER_BATCH_FLUSH_FAILED
}
